services:
  - type: web
    name: gmail-intelligence-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: "8080"
    healthCheckPath: /api/health
    autoDeploy: true